version: '3.9'

services:
  webserver:
    image: php:7.4-apache
    ports:
      - "8080:80"
    volumes:
      - ./site:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/conf.d/php.ini
    depends_on:
      - database
    environment:
      - MYSQL_HOST=database
      - MYSQL_USER=paugetc
      - MYSQL_PASSWORD=Capa1677
      - MYSQL_DATABASE=BIBYdex
    command: /bin/bash -c "if [ ! -f /var/www/html/.initialized ]; then docker-php-ext-install pdo_mysql && touch /var/www/html/.initialized; fi && apache2-foreground"
    restart: always

  database:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: Capa1677
      MYSQL_DATABASE: BIBYdex
      MYSQL_USER: paugetc
      MYSQL_PASSWORD: Capa1677
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: database
      MYSQL_ROOT_PASSWORD: Capa1677
    ports:
      - "8181:80"
    depends_on:
      - database
    restart: always

  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - database
    command: sh -c "npm install && node app.js"
