FROM php:7.4-apache

# Install necessary PHP extensions
RUN docker-php-ext-install mysqli pdo pdo_mysql

# Copy site content
COPY ./site /var/www/html/

# Copy custom php.ini settings
COPY ./php/php.ini /usr/local/etc/php/conf.d/

# Enable Apache mod_rewrite
RUN a2enmod rewrite

# Set the working directory
WORKDIR /var/www/html