version: '3'

services:
  webserver:
    image: php:7.4-apache
    ports:
      - "8080:80"
    volumes:
      - ./site:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/conf.d/php.ini  # Ajout de cette ligne
    depends_on:
      - database
    environment:
      - MYSQL_HOST=database
      - MYSQL_USER=paugetc
      - MYSQL_PASSWORD=Capa1677
      - MYSQL_DATABASE=BIBYdex

  database:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: BIBYdex
      MYSQL_USER: paugetc
      MYSQL_PASSWORD: Capa1677

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: database
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "8181:80"
    depends_on:
      - database
